!> Routines to read in equilibrium representation generated by GVEC
!!
!! This routine is intended for use with model 180. The 2D Fourier, 1D spline representation
!! in GVEC is already pre-processed within the code and converted to the 2D Bezier finite element, 
!! 1D Fourier representation in JOREK, contained in the import file. 

!! The import file contains the degrees of freedom at each node as separate arrays, which are 
!! read in, assuming nodes are ordered along each flux surface, extending radially outwards from 
!! the axis to plasma boundary.
module mod_import_gvec
implicit none
contains

subroutine import_gvec(node_list, element_list, file_name, ierr)
  use data_structure
  use phys_module

  type(type_node_list),    intent(inout)  :: node_list
  type(type_element_list), intent(inout)  :: element_list
  character*(*),           intent(in)     :: file_name       ! gvec import file name
  integer,                 intent(inout)  :: ierr            ! Error status
  
  logical                                 :: is_test = .false.

  call read_gvec_import(node_list, element_list, file_name, is_test, ierr)
end subroutine import_gvec

! Read data from GVEC import file into arrays of fourier harmonics for each degree of freedom
subroutine read_gvec_import(node_list, element_list, file_name, is_test, ierr)
  use tr_module
  use data_structure
  use phys_module
  
  type(type_node_list),    intent(inout)  :: node_list
  type(type_element_list), intent(inout)  :: element_list
  character*(*),           intent(in)     :: file_name       ! gvec import file name
  logical,                 intent(in)     :: is_test         ! true if routine is called for testing
  integer,                 intent(inout)  :: ierr            ! error status
  
  ! --- Local variables ---
  ! GVEC data
  integer          :: n_rad, n_theta, n_phi            ! Number of radial, poloidal and toroidal points
  integer          :: coord_type, num_periods, asym    ! GVEC coordinate type, number of field periods, equilibrium symmetry
  integer          :: m_max, n_max, n_modes            ! Maximum poloidal mode number, maximum toroidal mode number, number of modes
  integer          :: sin_range(2), cos_range(2)       ! Indices in fourier representation for sinusoidal and cosinusoidal modes
  real, allocatable        :: R_four(:, :, :), R_four_s(:, :, :), R_four_t(:, :, :), R_four_st(:, :, :)                 ! Arrays for node positions in fourier representation (i_theta, i_rad, i_four) 
  real, allocatable        :: Z_four(:, :, :), Z_four_s(:, :, :), Z_four_t(:, :, :), Z_four_st(:, :, :)                 ! Arrays for node Z positions in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: P_four(:, :, :), P_four_s(:, :, :), P_four_t(:, :, :), P_four_st(:, :, :)                 ! Arrays for node scalar pressure positions in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: B_R_four(:, :, :), B_R_four_s(:, :, :), B_R_four_t(:, :, :), B_R_four_st(:, :, :)         ! Arrays for node B_R in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: B_Z_four(:, :, :), B_Z_four_s(:, :, :), B_Z_four_t(:, :, :), B_Z_four_st(:, :, :)         ! Arrays for node B_Z in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: B_phi_four(:, :, :), B_phi_four_s(:, :, :), B_phi_four_t(:, :, :), B_phi_four_st(:, :, :) ! Arrays for node B_phi in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: J_R_four(:, :, :), J_R_four_s(:, :, :), J_R_four_t(:, :, :), J_R_four_st(:, :, :)         ! Arrays for node J_R in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: J_Z_four(:, :, :), J_Z_four_s(:, :, :), J_Z_four_t(:, :, :), J_Z_four_st(:, :, :)         ! Arrays for node J_Z in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: J_phi_four(:, :, :), J_phi_four_s(:, :, :), J_phi_four_t(:, :, :), J_phi_four_st(:, :, :) ! Arrays for node J_phi in fourier representation (i_theta, i_rad, i_four)
#ifdef USE_EXT_FIELD
  real, allocatable        :: B_vac_R_four(:, :, :), B_vac_R_four_s(:, :, :), B_vac_R_four_t(:, :, :), B_vac_R_four_st(:, :, :)         ! Arrays for node B_vac_R in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: B_vac_Z_four(:, :, :), B_vac_Z_four_s(:, :, :), B_vac_Z_four_t(:, :, :), B_vac_Z_four_st(:, :, :)         ! Arrays for node B_vac_Z in fourier representation (i_theta, i_rad, i_four)
  real, allocatable        :: B_vac_phi_four(:, :, :), B_vac_phi_four_s(:, :, :), B_vac_phi_four_t(:, :, :), B_vac_phi_four_st(:, :, :) ! Arrays for node B_vac_phi in fourier representation (i_theta, i_rad, i_four)
#endif

  ! JOREK grid
  integer          :: n_index_start, n_element_start, n_node_start

  ! General
  integer          :: idx, i_rad, i_theta, i_node, i_elm, itor, i_order, i_vertex        ! Generic, radial, poloidal, node, element, toroidal harmonic, DOF order, and vertex indices
  integer          :: ivp, ivm, node_iv, node_ivp, node_ivm                              ! Adjacent nodes to current vertex for calculating element size
  real*8           :: delta_rm, delta_zm, delta_rp, delta_zp, dir_2, dir_3               ! Variables for element size and directions
  real*8           :: s_factor, theta_factor
 
  ! Smoothing variables at s=0
  real*8           :: R_average, Z_average
  real*8           :: BR_average, BZ_average, Bphi_average
  real*8           :: JR_average, JZ_average, Jphi_average
#ifdef USE_EXT_FIELD
  real*8           :: BvacR_average, BvacZ_average, Bvacphi_average
#endif

  integer          :: in_gvec=11                          ! Input stream from gvec
  integer          :: iostatus=0                          ! Error flag for reading vacuum field
  integer          :: n_max_jorek = (n_coord_tor-1)/2     ! Maximum toroidal mode number in JOREK

#if !(JOREK_MODEL == 180)
  write(*,*) 'Equilibrium fields can only be read for stellarator initialisation models!'
  stop
#else
  if (n_order .ne. 3) then
    write(*,*) 'The GVEC import can only be used with cubic finite elements!'
    stop
  endif
  ! Read equilibrium parameters
  open(in_gvec, file=trim(file_name), status='old', iostat=ierr, form='formatted', access='sequential')
  if (ierr /= 0) then
    write(*, *) "Cannot open GVEC file..."
    stop
  end if
  ! Skip header lines
  do idx=1, 1000
    read(in_gvec, *, iostat=ierr) n_rad, n_theta, n_phi
    if (ierr .eq. 0) exit
  enddo
  if (idx .gt. 1000) then 
    write(*,*) "Number of header lines in GVEC import is > 1000 - something must be wrong."
    stop
  endif
  write(*, *)  "n_rad    n_theta    n_phi: ", n_rad, n_theta, n_phi
  if ((.not. is_test) .and. ((n_theta .ne. n_tht) .or. (n_rad .ne. n_flux))) then
    write(*, *) "Number of radial and poloidal points does not match values in input file: ", n_rad, n_flux, n_theta, n_tht
    stop
  endif
  read(in_gvec,*)
  read(in_gvec, *) coord_type, num_periods, asym, m_max, n_max, n_modes, sin_range(:), cos_range(:)
  write(*, *) "nfp    asym    m_max    n_max", num_periods, asym, m_max, n_max
  if (n_coord_period .ne. num_periods) then
    write(*, *) "Number of field periods in GVEC equilibrium does not match input file: ", num_periods, n_coord_period
    stop
  endif
  ! For stellarators, a sub-section of the full torus can only be modeled, if it contains a whole number of stellarator field periods
  ! e.g. for a 4 field period stellarator, n_period = 1, 2 or 4
  if (mod(n_coord_period, n_period) .ne. 0) then
    write(*, *) "Number of periods must be a factor of number of field periods: ", n_period, n_coord_period
    stop
  endif

  ! Check JOREK is compiled correctly from equilibrium
  if (n_coord_tor .lt. n_modes) then
    write(*,*) "WARNING: Number of modes in JOREK is less than in GVEC! (n_coord_tor, n_modes):" , n_coord_tor, n_modes
    write(*,*) "         Continuing with partial import of toroidal modes."
  else if (n_coord_tor .gt. n_modes) then
    write(*, *) "ERROR: Number of modes in JOREK must be less than or equal to GVEC representation! (n_coord_tor, n_modes):" , n_coord_tor, n_modes
    stop
  endif

  ! Read fourier representation
  write(*, *) "Allocating data for grid"
  call tr_allocate(R_four, 1, n_theta, 1, n_rad, 1, n_modes,          "R_four", CAT_GRID)
  call tr_allocate(R_four_s, 1, n_theta, 1, n_rad, 1, n_modes,        "R_four_s", CAT_GRID)
  call tr_allocate(R_four_t, 1, n_theta, 1, n_rad, 1, n_modes,        "R_four_t", CAT_GRID)
  call tr_allocate(R_four_st, 1, n_theta, 1, n_rad, 1, n_modes,       "R_four_st", CAT_GRID)
  call tr_allocate(Z_four, 1, n_theta, 1, n_rad, 1, n_modes,          "Z_four", CAT_GRID)
  call tr_allocate(Z_four_s, 1, n_theta, 1, n_rad, 1, n_modes,        "Z_four_s", CAT_GRID)
  call tr_allocate(Z_four_t, 1, n_theta, 1, n_rad, 1, n_modes,        "Z_four_t", CAT_GRID)
  call tr_allocate(Z_four_st, 1, n_theta, 1, n_rad, 1, n_modes,       "Z_four_st", CAT_GRID)
  call tr_allocate(P_four, 1, n_theta, 1, n_rad, 1, n_modes,          "P_four", CAT_GRID)
  call tr_allocate(P_four_s, 1, n_theta, 1, n_rad, 1, n_modes,        "P_four_s", CAT_GRID)
  call tr_allocate(P_four_t, 1, n_theta, 1, n_rad, 1, n_modes,        "P_four_t", CAT_GRID)
  call tr_allocate(P_four_st, 1, n_theta, 1, n_rad, 1, n_modes,       "P_four_st", CAT_GRID)
  call tr_allocate(B_R_four, 1, n_theta, 1, n_rad, 1, n_modes,        "B_R_four", CAT_GRID)
  call tr_allocate(B_R_four_s, 1, n_theta, 1, n_rad, 1, n_modes,      "B_R_four_s", CAT_GRID)
  call tr_allocate(B_R_four_t, 1, n_theta, 1, n_rad, 1, n_modes,      "B_R_four_t", CAT_GRID)
  call tr_allocate(B_R_four_st, 1, n_theta, 1, n_rad, 1, n_modes,     "B_R_four_st", CAT_GRID)
  call tr_allocate(B_Z_four, 1, n_theta, 1, n_rad, 1, n_modes,        "B_Z_four", CAT_GRID)
  call tr_allocate(B_Z_four_s, 1, n_theta, 1, n_rad, 1, n_modes,      "B_Z_four_s", CAT_GRID)
  call tr_allocate(B_Z_four_t, 1, n_theta, 1, n_rad, 1, n_modes,      "B_Z_four_t", CAT_GRID)
  call tr_allocate(B_Z_four_st, 1, n_theta, 1, n_rad, 1, n_modes,     "B_Z_four_st", CAT_GRID)
  call tr_allocate(B_phi_four, 1, n_theta, 1, n_rad, 1, n_modes,      "B_phi_four", CAT_GRID)
  call tr_allocate(B_phi_four_s, 1, n_theta, 1, n_rad, 1, n_modes,    "B_phi_four_s", CAT_GRID)
  call tr_allocate(B_phi_four_t, 1, n_theta, 1, n_rad, 1, n_modes,    "B_phi_four_t", CAT_GRID)
  call tr_allocate(B_phi_four_st, 1, n_theta, 1, n_rad, 1, n_modes,   "B_phi_four_st", CAT_GRID)
  call tr_allocate(J_R_four, 1, n_theta, 1, n_rad, 1, n_modes,        "J_R_four", CAT_GRID)
  call tr_allocate(J_R_four_s, 1, n_theta, 1, n_rad, 1, n_modes,      "J_R_four_s", CAT_GRID)
  call tr_allocate(J_R_four_t, 1, n_theta, 1, n_rad, 1, n_modes,      "J_R_four_t", CAT_GRID)
  call tr_allocate(J_R_four_st, 1, n_theta, 1, n_rad, 1, n_modes,     "J_R_four_st", CAT_GRID)
  call tr_allocate(J_Z_four, 1, n_theta, 1, n_rad, 1, n_modes,        "J_Z_four", CAT_GRID)
  call tr_allocate(J_Z_four_s, 1, n_theta, 1, n_rad, 1, n_modes,      "J_Z_four_s", CAT_GRID)
  call tr_allocate(J_Z_four_t, 1, n_theta, 1, n_rad, 1, n_modes,      "J_Z_four_t", CAT_GRID)
  call tr_allocate(J_Z_four_st, 1, n_theta, 1, n_rad, 1, n_modes,     "J_Z_four_st", CAT_GRID)
  call tr_allocate(J_phi_four, 1, n_theta, 1, n_rad, 1, n_modes,      "J_phi_four", CAT_GRID)
  call tr_allocate(J_phi_four_s, 1, n_theta, 1, n_rad, 1, n_modes,    "J_phi_four_s", CAT_GRID)
  call tr_allocate(J_phi_four_t, 1, n_theta, 1, n_rad, 1, n_modes,    "J_phi_four_t", CAT_GRID)
  call tr_allocate(J_phi_four_st, 1, n_theta, 1, n_rad, 1, n_modes,   "J_phi_four_st", CAT_GRID)
#ifdef USE_EXT_FIELD
  call tr_allocate(B_vac_R_four, 1, n_theta, 1, n_rad, 1, n_modes,        "B_vac_R_four", CAT_GRID)
  call tr_allocate(B_vac_R_four_s, 1, n_theta, 1, n_rad, 1, n_modes,      "B_vac_R_four_s", CAT_GRID)
  call tr_allocate(B_vac_R_four_t, 1, n_theta, 1, n_rad, 1, n_modes,      "B_vac_R_four_t", CAT_GRID)
  call tr_allocate(B_vac_R_four_st, 1, n_theta, 1, n_rad, 1, n_modes,     "B_vac_R_four_st", CAT_GRID)
  call tr_allocate(B_vac_Z_four, 1, n_theta, 1, n_rad, 1, n_modes,        "B_vac_Z_four", CAT_GRID)
  call tr_allocate(B_vac_Z_four_s, 1, n_theta, 1, n_rad, 1, n_modes,      "B_vac_Z_four_s", CAT_GRID)
  call tr_allocate(B_vac_Z_four_t, 1, n_theta, 1, n_rad, 1, n_modes,      "B_vac_Z_four_t", CAT_GRID)
  call tr_allocate(B_vac_Z_four_st, 1, n_theta, 1, n_rad, 1, n_modes,     "B_vac_Z_four_st", CAT_GRID)
  call tr_allocate(B_vac_phi_four, 1, n_theta, 1, n_rad, 1, n_modes,      "B_vac_phi_four", CAT_GRID)
  call tr_allocate(B_vac_phi_four_s, 1, n_theta, 1, n_rad, 1, n_modes,    "B_vac_phi_four_s", CAT_GRID)
  call tr_allocate(B_vac_phi_four_t, 1, n_theta, 1, n_rad, 1, n_modes,    "B_vac_phi_four_t", CAT_GRID)
  call tr_allocate(B_vac_phi_four_st, 1, n_theta, 1, n_rad, 1, n_modes,   "B_vac_phi_four_st", CAT_GRID)
#endif /*USE_EXT_FIELD*/
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') R_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') R_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') R_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') R_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Z_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Z_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Z_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') Z_four_st

  ! Pressure profile - really only n=0 component is needed
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') P_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') P_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') P_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') P_four_st
  
  ! A_phi profile - currently not read in
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_st

  ! B profiles
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_R_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_Z_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_Z_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_Z_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_Z_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_phi_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_phi_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_phi_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_phi_four_st

  ! J profiles
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_R_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_R_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_R_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_R_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_Z_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_Z_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_Z_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_Z_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_phi_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_phi_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_phi_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') J_phi_four_st
  
  ! B_vac profiles
  ! B_vac_R/Z/phi are in the same cylindrical (R, Z, phi_physical) convention as B_R/Z/phi above.
  ! The gvec2jorek utility handles the GVEC internal->physical phi conversion before writing.
#ifdef USE_EXT_FIELD
  read(in_gvec, '(A)', iostat=ierr)
  if (ierr /= 0) then
    write(*,*) 'ERROR: USE_EXT_FIELD=1 but gvec2jorek.dat does not contain B_vac blocks.'
    write(*,*) 'Regenerate gvec2jorek.dat with a GVEC version that exports B_vac_R/Z/phi.'
    stop
  end if
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_R_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_R_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_R_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_R_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_Z_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_Z_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_Z_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_Z_four_st
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_phi_four
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_phi_four_s
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_phi_four_t
  read(in_gvec, '(A)')
  read(in_gvec,'(*(6(e23.15,:,1X),/))') B_vac_phi_four_st
#endif /*USE_EXT_FIELD*/
  close(in_gvec)

  ! Zero element and node variables
  n_element_start  = element_list%n_elements
  n_node_start     = node_list%n_nodes
  do idx=n_node_start+1,n_nodes_max
    node_list%node(idx)%x        = 0.d0
    node_list%node(idx)%values   = 0.d0
    node_list%node(idx)%index    = 0
    node_list%node(idx)%boundary = 0
  enddo
  do i_elm=n_element_start+1,n_elements_max
    element_list%element(i_elm)%vertex     = 0
    element_list%element(i_elm)%size       = 0.d0
    element_list%element(i_elm)%neighbours = 0
  enddo

  ! Set number of elements and nodes and check that the grid memory allocation is sufficient
  n_index_start = 0
  do idx=1,n_node_start
    n_index_start = max(n_index_start,maxval(node_list%node(idx)%index(:)))
  enddo
  element_list%n_elements  = n_element_start  + (n_rad-1)*n_theta
  node_list%n_nodes        = n_node_start     + n_rad*n_theta
  if (element_list%n_elements > n_elements_max) then
    write(*, *)  "ERROR: n_elements > n_elements_max - increase maximum number of elements: ", element_list%n_elements, n_elements_max
    stop
  endif
  if (node_list%n_nodes > n_nodes_max) then
    write(*, *)  "ERROR: n_nodes > n_nodes_max - increase maximum number of nodes: ", node_list%n_nodes, n_nodes_max
    stop
  endif

  ! Define elements based on nodes
  do i_rad=1,n_rad-1
   do i_theta=1,n_theta
      i_node  = n_theta*(i_rad-1) + i_theta
      i_elm = n_element_start + i_node
      element_list%element(i_elm)%vertex(1) = n_node_start + (i_rad-1)*n_theta + i_theta
      element_list%element(i_elm)%vertex(4) = n_node_start + (i_rad-1)*n_theta + i_theta + 1
      element_list%element(i_elm)%vertex(3) = n_node_start + i_rad*n_theta + i_theta + 1
      element_list%element(i_elm)%vertex(2) = n_node_start + i_rad*n_theta + i_theta
  
      ! Correct element nodes if index is last poloidal node
      if (i_theta .eq. n_theta) then
        element_list%element(i_elm)%vertex(4) = n_node_start + (i_rad-1)*n_theta + 1
        element_list%element(i_elm)%vertex(3) = n_node_start + i_rad*n_theta    + 1
      endif    
    enddo
  enddo
  
  ! Define node dofs
  s_factor = 1.0 * bloating_factor / (n_rad - 1)
  theta_factor = 2 * PI / (n_theta)
  do i_rad=1,n_rad
    do i_theta=1,n_theta
      i_node = n_node_start + n_theta*(i_rad-1) + i_theta
      
      ! Read in pressure
      node_list%node(i_node)%pressure(1) = P_four(i_theta, i_rad, n_max+1)  ! n_max+1 => i_tor=1
      node_list%node(i_node)%pressure(2) = P_four_s(i_theta, i_rad, n_max+1) * s_factor * 1.0 / 3.0
      node_list%node(i_node)%pressure(3) = P_four_t(i_theta, i_rad, n_max+1) * theta_factor * 1.0 / 3.0
      node_list%node(i_node)%pressure(4) = P_four_st(i_theta, i_rad, n_max+1) * s_factor * theta_factor * 1.0 / 9.0

      ! Read in radial coordinate - Assumes that the imported GVEC data is uniform radially
      node_list%node(i_node)%r_tor_eq(1) = (i_rad-1) * bloating_factor / float(n_rad-1)
      node_list%node(i_node)%r_tor_eq(2) = s_factor * 1.0 / 3.0
      node_list%node(i_node)%r_tor_eq(3) = 0.0
      node_list%node(i_node)%r_tor_eq(4) = 0.0

      do idx=1, n_modes
        if ((idx .gt. n_max_jorek) .and. (idx .le. n_max)) cycle   ! Skip higher sinusoidal modes
        if (idx .gt. n_max+1+n_max_jorek) cycle                   ! Skip higher cosinusoidal modes

        call get_gvec_mode_idx(idx, n_max, sin_range, cos_range, itor)

        ! Modify derivative dofs by conversion factor (1/3) for cubic hermite elements to bezier representation
        ! The additional s and theta factor are to compensate for element size being normalised ... ?
        node_list%node(i_node)%X(itor,1,1)        = R_four(i_theta, i_rad, idx)
        node_list%node(i_node)%X(itor,1,2)        = Z_four(i_theta, i_rad, idx)
        node_list%node(i_node)%X(itor,2,1)        = R_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%X(itor,2,2)        = Z_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%X(itor,3,1)        = R_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%X(itor,3,2)        = Z_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%X(itor,4,1)        = R_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        node_list%node(i_node)%X(itor,4,2)        = Z_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0

        ! Read B field R, Z, phi components
        node_list%node(i_node)%b_field(itor, 1, 1) = B_R_four(i_theta, i_rad, idx)
        node_list%node(i_node)%b_field(itor, 2, 1) = B_R_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%b_field(itor, 3, 1) = B_R_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%b_field(itor, 4, 1) = B_R_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        node_list%node(i_node)%b_field(itor, 1, 2) = B_Z_four(i_theta, i_rad, idx)
        node_list%node(i_node)%b_field(itor, 2, 2) = B_Z_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%b_field(itor, 3, 2) = B_Z_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%b_field(itor, 4, 2) = B_Z_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        node_list%node(i_node)%b_field(itor, 1, 3) = B_phi_four(i_theta, i_rad, idx)
        node_list%node(i_node)%b_field(itor, 2, 3) = B_phi_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%b_field(itor, 3, 3) = B_phi_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%b_field(itor, 4, 3) = B_phi_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        
        ! Read J field R, Z, phi components
        node_list%node(i_node)%j_field(itor, 1, 1) = J_R_four(i_theta, i_rad, idx)
        node_list%node(i_node)%j_field(itor, 2, 1) = J_R_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%j_field(itor, 3, 1) = J_R_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%j_field(itor, 4, 1) = J_R_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        node_list%node(i_node)%j_field(itor, 1, 2) = J_Z_four(i_theta, i_rad, idx)
        node_list%node(i_node)%j_field(itor, 2, 2) = J_Z_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%j_field(itor, 3, 2) = J_Z_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%j_field(itor, 4, 2) = J_Z_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        node_list%node(i_node)%j_field(itor, 1, 3) = J_phi_four(i_theta, i_rad, idx)
        node_list%node(i_node)%j_field(itor, 2, 3) = J_phi_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%j_field(itor, 3, 3) = J_phi_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%j_field(itor, 4, 3) = J_phi_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0

#ifdef USE_EXT_FIELD
        ! Read vacuum B field R, Z, phi components
        node_list%node(i_node)%b_vac_field(itor, 1, 1) = B_vac_R_four(i_theta, i_rad, idx)
        node_list%node(i_node)%b_vac_field(itor, 2, 1) = B_vac_R_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%b_vac_field(itor, 3, 1) = B_vac_R_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%b_vac_field(itor, 4, 1) = B_vac_R_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        node_list%node(i_node)%b_vac_field(itor, 1, 2) = B_vac_Z_four(i_theta, i_rad, idx)
        node_list%node(i_node)%b_vac_field(itor, 2, 2) = B_vac_Z_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%b_vac_field(itor, 3, 2) = B_vac_Z_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%b_vac_field(itor, 4, 2) = B_vac_Z_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
        node_list%node(i_node)%b_vac_field(itor, 1, 3) = B_vac_phi_four(i_theta, i_rad, idx)
        node_list%node(i_node)%b_vac_field(itor, 2, 3) = B_vac_phi_four_s(i_theta, i_rad, idx) * s_factor * 1.0 / 3.0
        node_list%node(i_node)%b_vac_field(itor, 3, 3) = B_vac_phi_four_t(i_theta, i_rad, idx) * theta_factor * 1.0 / 3.0
        node_list%node(i_node)%b_vac_field(itor, 4, 3) = B_vac_phi_four_st(i_theta, i_rad, idx) * s_factor * theta_factor * 1.0 / 9.0
#endif /*USE_EXT_FIELD or USE_DOMM*/
      enddo
      
      ! Determine if node is on the boundary
      node_list%node(i_node)%boundary = 0
      if (i_rad .eq. n_rad) node_list%node(i_node)%boundary = 2
      
      ! Share 4 degrees of freedom for all nodes on the grid axis and flag the axis nodes.
      if (treat_axis) then
        if (i_rad .eq. 1) then
          node_list%node(i_node)%index(1) = 1
          node_list%node(i_node)%index(2) = 2
          node_list%node(i_node)%index(3) = 3
          node_list%node(i_node)%index(4) = 4
          n_index_start = 4
          node_list%node(i_node)%axis_node = .true.
          node_list%node(i_node)%axis_dof = 3
        else
          do i_order=1,n_order+1
            node_list%node(i_node)%index(i_order) = n_index_start + i_order
          end do
          n_index_start = n_index_start + n_order + 1
          node_list%node(i_node)%axis_node = .false.
        end if
      ! Fix all axis nodes to have the same indices in global matrix structure is force_central_node = .t.
      else if (force_central_node .and. (i_rad .eq. 1)) then
        node_list%node(i_node)%index(1) = 1

        if (i_theta .eq. 1) n_index_start = n_index_start + 1
        node_list%node(i_node)%index(2) = n_index_start + 1
        node_list%node(i_node)%index(3) = n_index_start + 2
        node_list%node(i_node)%index(4) = n_index_start + 3
        n_index_start = n_index_start + n_order
      else
        do i_order=1,n_order+1
          node_list%node(i_node)%index(i_order) = n_index_start + i_order
        end do
        n_index_start = n_index_start + n_order+1
      end if
      
      if (fix_axis_nodes .and. (i_rad .eq. 1)) node_list%node(i_node)%axis_node = .true.

      node_list%node(i_node)%constrained=.false.
    enddo
  enddo

  ! fill in the size of the elements - in reality this is just the direction of the vertex in the element
  do i_elm=n_element_start+1 , element_list%n_elements   
    do i_vertex=1, 4                    ! over 4 corners of an element
  
      ivp = mod(i_vertex,4)   + 1         ! vertex with index one higher
      ivm = mod(i_vertex+2,4) + 1         ! vertex with index one below
  
      node_iv  = element_list%element(i_elm)%vertex(i_vertex)
      node_ivp = element_list%element(i_elm)%vertex(ivp)
      node_ivm = element_list%element(i_elm)%vertex(ivm)
  
      if ((i_vertex .eq. 1) .or. (i_vertex .eq.3)) then
        delta_Rp = node_list%node(node_ivp)%X(1,1,1) - node_list%node(node_iv)%X(1,1,1)
        delta_Zp = node_list%node(node_ivp)%X(1,1,2) - node_list%node(node_iv)%X(1,1,2)
        dir_2    = delta_Rp * node_list%node(node_iv)%X(1,2,1) + delta_Zp * node_list%node(node_iv)%X(1,2,2)
  
        delta_Rm = node_list%node(node_ivm)%X(1,1,1) - node_list%node(node_iv)%X(1,1,1)
        delta_Zm = node_list%node(node_ivm)%X(1,1,2) - node_list%node(node_iv)%X(1,1,2)
        dir_3    = delta_Rm * node_list%node(node_iv)%X(1,3,1) + delta_Zm * node_list%node(node_iv)%X(1,3,2)
      else
        delta_Rp = node_list%node(node_ivp)%X(1,1,1) - node_list%node(node_iv)%X(1,1,1)
        delta_Zp = node_list%node(node_ivp)%X(1,1,2) - node_list%node(node_iv)%X(1,1,2)
        dir_3    = delta_Rp * node_list%node(node_iv)%X(1,3,1) + delta_Zp * node_list%node(node_iv)%X(1,3,2)
  
        delta_Rm = node_list%node(node_ivm)%X(1,1,1) - node_list%node(node_iv)%X(1,1,1)
        delta_Zm = node_list%node(node_ivm)%X(1,1,2) - node_list%node(node_iv)%X(1,1,2)
        dir_2    = delta_Rm * node_list%node(node_iv)%X(1,2,1) + delta_Zm * node_list%node(node_iv)%X(1,2,2)
      endif
  
      if (dir_2 .ne. 0.d0) then
        dir_2 = dir_2 / abs(dir_2)
      else
        dir_2 = 1.d0
      endif
      if (dir_3 .ne. 0.d0) then
        dir_3 = dir_3 / abs(dir_3)
      else
        dir_3 = -1.d0
        if (i_vertex.eq.1) dir_3 = 1.d0              ! admittedly not very elegant
      endif
  
      element_list%element(i_elm)%size(i_vertex,1) = 1.d0
      element_list%element(i_elm)%size(i_vertex,2) = dir_2
      element_list%element(i_elm)%size(i_vertex,3) = dir_3
      element_list%element(i_elm)%size(i_vertex,4) = element_list%element(i_elm)%size(i_vertex,2) * element_list%element(i_elm)%size(i_vertex,3)
      if (fix_axis_nodes) then
        i_node = element_list%element(i_elm)%vertex(i_vertex)
        if (node_list%node(i_node)%axis_node) then
          element_list%element(i_elm)%size(i_vertex,3) = 0.d0
          element_list%element(i_elm)%size(i_vertex,4) = 0.d0
        end if
      end if
    enddo
  enddo

  ! Smooth axis points - GVEC axis points are shifted from s=0 for numerical stability. The points need to be averaged onto s=0
  do idx=1, n_coord_tor
#ifdef USE_EXT_FIELD
    R_average=0.0; Z_average=0.0; BR_average=0.0; BZ_average=0.0; BvacR_average=0.0; BvacZ_average=0.0;
#else
    R_average=0.0; Z_average=0.0; BR_average=0.0; BZ_average=0.0;
#endif /*USE_EXT_FIELD*/
    do i_node=1, n_tht
      R_average     = R_average   + node_list%node(i_node)%x(idx, 1, 1)
      Z_average     = Z_average   + node_list%node(i_node)%x(idx, 1, 2)
      BR_average    = BR_average  + node_list%node(i_node)%b_field(idx, 1, 1)
      BZ_average    = BZ_average  + node_list%node(i_node)%b_field(idx, 1, 2)
#ifdef USE_EXT_FIELD
      BvacR_average = BvacR_average  + node_list%node(i_node)%b_vac_field(idx, 1, 1)
      BvacZ_average = BvacZ_average  + node_list%node(i_node)%b_vac_field(idx, 1, 2)
#endif /*USE_EXT_FIELD*/
    enddo
    do i_node=1, n_tht
      node_list%node(i_node)%x(idx, 1, 1) = R_average   / n_tht
      node_list%node(i_node)%x(idx, 3, 1) = 0.0
      !node_list%node(i_node)%x(idx, 4, 1) = 0.0
      node_list%node(i_node)%x(idx, 1, 2) = Z_average   / n_tht
      node_list%node(i_node)%x(idx, 3, 2) = 0.0
      !node_list%node(i_node)%x(idx, 4, 2) = 0.0
      !node_list%node(i_node)%b_field(idx, 1, 1) = BR_average  / n_tht
      node_list%node(i_node)%b_field(idx, 3, 1) = 0.0
      node_list%node(i_node)%b_field(idx, 4, 1) = 0.0
      !node_list%node(i_node)%b_field(idx, 1, 1) = BZ_average  / n_tht
      ! Not sure why this is commented out? I think it should be b_field(idx,1,2) for Z coordinate anyway.
      node_list%node(i_node)%b_field(idx, 3, 2) = 0.0
      node_list%node(i_node)%b_field(idx, 4, 2) = 0.0
#ifdef USE_EXT_FIELD
      !node_list%node(i_node)%b_vac_field(idx, 1, 1) = BvacR_average  / n_tht
      node_list%node(i_node)%b_vac_field(idx, 3, 1) = 0.0
      node_list%node(i_node)%b_vac_field(idx, 4, 1) = 0.0
      !node_list%node(i_node)%b_vac_field(idx, 1, 2) = BvacZ_average  / n_tht
      node_list%node(i_node)%b_vac_field(idx, 3, 2) = 0.0
      node_list%node(i_node)%b_vac_field(idx, 4, 2) = 0.0
#endif /*USE_EXT_FIELD*/
    enddo
  enddo

  ! De-allocate DOFs
  call tr_deallocate(R_four,          "R_four", CAT_GRID)
  call tr_deallocate(R_four_s,        "R_four_s", CAT_GRID)
  call tr_deallocate(R_four_t,        "R_four_t", CAT_GRID)
  call tr_deallocate(R_four_st,       "R_four_st", CAT_GRID)
  call tr_deallocate(Z_four,          "Z_four", CAT_GRID)
  call tr_deallocate(Z_four_s,        "Z_four_s", CAT_GRID)
  call tr_deallocate(Z_four_t,        "Z_four_t", CAT_GRID)
  call tr_deallocate(Z_four_st,       "Z_four_st", CAT_GRID)
  call tr_deallocate(B_R_four,        "B_R_four", CAT_GRID)
  call tr_deallocate(B_R_four_s,      "B_R_four_s", CAT_GRID)
  call tr_deallocate(B_R_four_t,      "B_R_four_t", CAT_GRID)
  call tr_deallocate(B_R_four_st,     "B_R_four_st", CAT_GRID)
  call tr_deallocate(B_Z_four,        "B_Z_four", CAT_GRID)
  call tr_deallocate(B_Z_four_s,      "B_Z_four_s", CAT_GRID)
  call tr_deallocate(B_Z_four_t,      "B_Z_four_t", CAT_GRID)
  call tr_deallocate(B_Z_four_st,     "B_Z_four_st", CAT_GRID)
  call tr_deallocate(B_Phi_four,      "B_Phi_four", CAT_GRID)
  call tr_deallocate(B_Phi_four_s,    "B_Phi_four_s", CAT_GRID)
  call tr_deallocate(B_Phi_four_t,    "B_Phi_four_t", CAT_GRID)
  call tr_deallocate(B_Phi_four_st,   "B_Phi_four_st", CAT_GRID)
  call tr_deallocate(B_R_four,        "J_R_four", CAT_GRID)
  call tr_deallocate(B_R_four_s,      "J_R_four_s", CAT_GRID)
  call tr_deallocate(B_R_four_t,      "J_R_four_t", CAT_GRID)
  call tr_deallocate(B_R_four_st,     "J_R_four_st", CAT_GRID)
  call tr_deallocate(B_Z_four,        "J_Z_four", CAT_GRID)
  call tr_deallocate(B_Z_four_s,      "J_Z_four_s", CAT_GRID)
  call tr_deallocate(B_Z_four_t,      "J_Z_four_t", CAT_GRID)
  call tr_deallocate(B_Z_four_st,     "J_Z_four_st", CAT_GRID)
  call tr_deallocate(B_Phi_four,      "J_Phi_four", CAT_GRID)
  call tr_deallocate(B_Phi_four_s,    "J_Phi_four_s", CAT_GRID)
  call tr_deallocate(B_Phi_four_t,    "J_Phi_four_t", CAT_GRID)
  call tr_deallocate(B_Phi_four_st,   "J_Phi_four_st", CAT_GRID)
#ifdef USE_EXT_FIELD
  call tr_deallocate(B_vac_R_four,        "B_vac_R_four", CAT_GRID)
  call tr_deallocate(B_vac_R_four_s,      "B_vac_R_four_s", CAT_GRID)
  call tr_deallocate(B_vac_R_four_t,      "B_vac_R_four_t", CAT_GRID)
  call tr_deallocate(B_vac_R_four_st,     "B_vac_R_four_st", CAT_GRID)
  call tr_deallocate(B_vac_Z_four,        "B_vac_Z_four", CAT_GRID)
  call tr_deallocate(B_vac_Z_four_s,      "B_vac_Z_four_s", CAT_GRID)
  call tr_deallocate(B_vac_Z_four_t,      "B_vac_Z_four_t", CAT_GRID)
  call tr_deallocate(B_vac_Z_four_st,     "B_vac_Z_four_st", CAT_GRID)
  call tr_deallocate(B_vac_Phi_four,      "B_vac_Phi_four", CAT_GRID)
  call tr_deallocate(B_vac_Phi_four_s,    "B_vac_Phi_four_s", CAT_GRID)
  call tr_deallocate(B_vac_Phi_four_t,    "B_vac_Phi_four_t", CAT_GRID)
  call tr_deallocate(B_vac_Phi_four_st,   "B_vac_Phi_four_st", CAT_GRID)
#endif /*USE_EXT_FIELD*/
#endif /*jorek_180*/

end subroutine read_gvec_import

! Convert from GVEC toroidal mode indexing to JOREK indexing
!
! GVEC lists sinusoidal modes from n=1 to n_max at indices n, followed by 
!   cosinusoidal modes from n=0 to n_max at indices n_max + n
! JOREK lists sinusoidal modes from n=1 to n_max at indices 2*n + 1, followed by
!  cosinusoidal modes from n=0 to n_max at indices 2*n
subroutine get_gvec_mode_idx(idx, n_max, sin_range, cos_range, itor)
  integer, intent(in)     :: idx, n_max, sin_range(2), cos_range(2)
  integer, intent(inout)  :: itor
  
  if (idx .gt. n_max) then
    ! cosine
    if (idx .eq. n_max + 1) then
      ! axisymmetric n=0
      itor = 1
    else
      itor = 2 * (idx - n_max - 1)  
    endif
  else
    ! sine
    itor = 2 * idx + 1
  endif 
end subroutine get_gvec_mode_idx

end module mod_import_gvec
